name: Playwright Tests
on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
            pip install -r requirements.txt
            playwright install --with-deps chromium

      - name: Run App from Docker Hub
        run: |
            
            docker pull dave0a/setupdocker-app:latest
            docker run -d -p 8081:8081 dave0a/setupdocker-app:latest

      - name: Wait for App
        run: sleep 10

      - name: Run Playwright tests
        run: sleep 10 
             pytest --tracing retain-on-failure
        env:
            BASE_URL: http://localhost:8081
            PYTHONPATH: .